epgsql/epgsql

README.md, include/epgsql.hrl, src/epgsql.erl
I've changed a bit `README.md` layout (preserving original content of file), I believe this improves readability significantly. You can check this out here: [burkov/epgsql](https://github.com/burkov/epgsql/tree/improve_readmemd)
Also fixed typing in `pgsql.erl` and added few examples into `README.md`
=> [Doc][Minor] Improve README.md

README.md
Some quick docs in the README.md per the PR comment.
=> Document int4range a bit

src/epgsql_sock.erl
Formerly, the `cancel` handler tried to use `inet:peername/1` to determine where to connect to issue the cancel command. This caused a crash when the connection hosting the timed-out query was over SSL, since you must instead call `ssl:peername/1` for SSL sockets.
The crash looked like this:
[error] CRASH REPORT Process <0.25743.31> with 2 neighbours exited
with reason: no function clause matching
prim_inet:peername({sslsocket,{gen_tcp,#Port<0.667326>,
tls_connection},<0.25810.31>})
in gen_fsm:terminate/7 line 622
You can reproduce this by connecting to a server over SSL and issuing a `pg_sleep(120)` command.
This patch just changes the `cancel` handler to honor the `mod` atom already stored in the fsm's `State`.
This leaves the code as it is so it connects over regular TCP even for SSL …
=> Properly cancel timed-out queries from SSL connections

include/epgsql_geometry.hrl
=> Work around some dependent types. Fixes dialyzer runs.

src/epgsql.erl
For version of PG below 9 the pg_type table has a different format this causes epgsql to fail to connect to AWS redshift as it is based on PG 8
=> Allow type cache query to fail

README.md, src/epgsql.erl
Fixing error in comments, added delete statement to the comments (with insert and update). Progressed in README.
=> Fixing error in comments, added delete statement to the

src/epgsql_sock.erl
Aggregate small packets into large one to reduce number of
port_command/2 calls, and eventually reduce number of packets.
=> epgsql_sock: aggregate small packets into one

src/epgsql_sock.erl
in some case when a user process got timeout and reconnected,
an old connection to postgres might stay hanging around for quite a while
=> close socket in terminate/2

.travis.yml, src/epgsql_wire.erl
Just make it work on Erlang 19
=> Make it compatible with Erlang 19. Add travis

include/epgsql.hrl, src/epgsql_wire.erl
=> Support unlocalized severity (V) error field, added in PostgreSQL 9.6

src/epgsql_fdatetime.erl
Avoid conflict with new floor function.
=> Fix for Erlang/OTP 20.0

.travis.yml, Makefile, test/epgsql_SUITE.erl, test/epgsql_cth.erl
This should (hopefuly) fix currently failing travis builds.
=> Fix travis builds; make tests more portable between PG versions

README.md, src/epgsql.erl
Fix for #146, plus fix for broken README
=> Fix `rebar3 edoc`. Cleanup and fix README. Fixes #146

.travis.yml, Makefile, rebar.config, rebar.config.script, src/datatypes/epgsql_codec_datetime.erl, src/epgsql.erl, src/epgsql_binary.erl, src/epgsql_codec.erl, src/epgsql_fdatetime.erl, src/epgsql_idatetime.erl, src/epgsql_sock.erl, src/epgsql_wire.erl, src/epgsqla.erl, src/epgsqli.erl, src/ewkb.erl
Uses rebar3 lint plugin. Fixes #141
=> Add elvis; fixes #141

test/epgsql_cth.erl
On my machine Ubunty 18.04 `postgres -V` output was `postgres (PostgreSQL) 10.4 (Ubuntu 10.4-0ubuntu0.18.04)` which is very difficult to parse
=> More reliable epgsql_cth:get_version

.travis.yml, rebar.config, src/epgsql.erl
erlang:get_stacktrace() was deprecated
=> Compatibility with Erlang 21

CHANGES, src/epgsql.app.src, src/epgsql.erl, src/epgsqla.erl, src/epgsqli.erl, test/epgsql_SUITE.erl
See #175 for detail. Bug was introduced in 4.2.0
=> Fix connect proplist

src/commands/epgsql_cmd_connect.erl, test/epgsql_SUITE.erl
Fix for #182.
Adds handling for all server-side errors in any state.
=> Handle all server errors. Fixes #182

src/epgsql.erl
Dialyzer is not so happy due to the wrong spec :)
=> Fix typespec since password may be a string() or a fun()

src/commands/epgsql_cmd_describe_portal.erl, test/epgsql_SUITE.erl, test/epgsql_incremental.erl
It was basically broken since 4.0.0 refactoring, but haven't been covered by tests.
=> Fix describe(_, portal, _); add tests

README.md
=> Document `epgsql:cancel/1`. Fixes #220

rebar.config
Version 0.3.0 exists, but it has some troubles working from non-default profile
=> Stick to rebar3_lint 0.2.0

src/epgsql_sock.erl
Imagine the following scenario:
We have fired an `epgsql:equery/squery` call and while getting the results back from PG server we are accumulating rows in the `epgsql_sock` state. While this is happening `epgsql_sock` process terminates abnormally. 
At this moment gen_server will try to print/format the State.
Given that we might have accumulated several hundred thousands or even million of rows in the state this will cause a memory spike and in the worst case scenario an OOM.
This solution tries to solve that problem by introducing another gen_server optional callback, `format_status`, where we replace the accumulated list in the rows with an atom stating `information_redacted`.
While looking at the code I realized that `format_status` could be used to remove the sensitive info  from …
=> Do not format certain attributes of State on abnormal epgsql sock termination

.github/workflows/ci.yml, Makefile
=> CI: add OTP-25, remove OTP-19, add PostgreSQL 14, 15

src/epgsql_sock.erl
This hack only made sense before OTP-26. And versions older than OTP-26 are getting phased-out, so we don't expect many users are going to be affected.
=> Remove gen_tcp async send hack
