epgsql/epgsql

- Makefile
When localhost is used, it can be substituted by ::1
Our pg_hba.conf allows 127.0.0.1 only, so it leads to the following issue:
```
psql: FATAL:  no pg_hba.conf entry for host "::1"
```
In order to avoid this, specify IPv4 addr explicitly
> Use 127.0.0.1 instead localhost to avoid IPv6 issues

- .travis.yml
- src/epgsql.erl
Since `query` was reserved keyword prior R16, it can't be used in erlang code. I just renamed it to make epgsql compatible with R15 again. See https://github.com/epgsql/epgsql/pull/53#issuecomment-73803153 for details.
> Rename query keyword

- src/epgsql.app.src
I've added information that is displayed in the hex.pm page for the package to the .app.src file.
> Add information to app file for hex package manager

- CHANGES
- src/epgsql.app.src
Bump's the version, and tags the repo so that we can push the "dialyzer_patched" version to hex.pm
> Bump version to add @jlouis666's dialyzer patch

- src/epgsql.app.src
- src/epgsql.erl
- test/epgsql_tests.erl
so that one can call e.g. epgsql:update_type_cache(C, [<<"my_enum1">>, <<"my_enum2">>])
> support custom types in prepared statements

- .travis.yml
Because now travis builds fail: it tries to install both `postgresql-contrib-9.5` & `postgresql-server-9.3`
> Explicit postgresql-contrib version in travis.yml

- src/epgsql.erl
Minor typespec fix. It's like #68, but fixes both row types.
> Fix squery_row, equery_row typespecs. Fixes #68

- README.md
- rebar.config
- src/epgsql.erl
- src/epgsqla.erl
- src/epgsqli.erl
- test/epgsql_cast.erl
- test/epgsql_incremental.erl
- test/epgsql_tests.erl
Maps can be used only on VM versions, that supports them, so, conditional compilation used.
For now maps are just converted to proplists early. But if at some moment we decide to drop support for Erlang < 17, we may start use maps internally.
> Make it possible to pass connect options as `map()`

- README.md
- src/epgsql.erl
- src/epgsql_sock.erl
- src/epgsqla.erl
- src/epgsqli.erl
- test/epgsql_cast.erl
- test/epgsql_incremental.erl
- test/epgsql_tests.erl
It's mostly for case, described in #112 and on this thread https://groups.google.com/forum/#!topic/epgsql/ePdg5-J6XZA
Also, `get_parameter` documented in README.
Not sure about the name, maybe somebody can suggest a better one?
Another open question is: should we return parsed status (as `atom() | {atom(), integer()}`) or raw value as binary string? Or maybe add option to read one of them (eg `get_cmd_status(C, raw), get_cmd_status(C, parsed)`).
> Add get_cmd_status function

- src/epgsql_sock.erl
- test/epgsql_incremental.erl
- test/epgsql_tests.erl
It's fix for #86 
So, now `UPDATE ... RETURNING ..` and `DELETE ... RETURNING ..` (and `INSERT .. RETURNING ..`, but I can't imagine such situation) will always return 4-tuple `{ok, Count, Columns, Rows}` from `squery`/`equery`.
Before this fix it was returning `{ok, 0}` when 0 rows were affected and this behaviour was inconsistent.
> Fix `UPDATE/DELETE ... RETURNING ..` returning 0 rows

- src/epgsql.erl
Actualize date and time typespecs.
The problem is that erlang `calendar` and postgresql `timestamp` have a bit different data ranges, plus, epgsql returns time seconds as floats.
https://www.postgresql.org/docs/current/static/datatype-datetime.html
Fixes #60
> Fix typespecs, related to date and time. Fixes #60.

- src/epgsql_binary.erl
- src/epgsql_types.erl
- test/data/test_schema.sql
- test/epgsql_tests.erl
Additionally, turn int4range and int8range into first-class binary types.
> Add int8range type support.

- README.md
- streaming.md
GitHub changed the way Markdown headings are parsed, so this change fixes it.
See [bryant1410/readmesfix](https://github.com/bryant1410/readmesfix) for more information.
Tackles bryant1410/readmesfix#1
> Fix broken headings in Markdown files

- src/epgsql.erl
- test/epgsql_SUITE.erl
- test/epgsql_cast.erl
- test/epgsql_incremental.erl
See #29 #111 #135 for details.
`with_transaction/2` uses `with_transaction/3`, but their default behaviours are different: `/3` reraises exception by-default, while `/2` returns `{rollback, Reason}`.
Reraise choosen as default because it won't hide any information.
> Add with_transaction/3.

- test/epgsql_SUITE.erl
- test/epgsql_cast.erl
- test/epgsql_cth.erl
- test/epgsql_incremental.erl
Just assert that in case of `gen_tcp:connect` error we first reply with error and then immediately stop epgsql_sock process.
> Add test case for connect network error

- include/protocol.hrl
- src/commands/epgsql_cmd_connect.erl
- src/epgsql_scram.erl
- test/data/test_schema.sql
- test/epgsql_SUITE.erl
- test/epgsql_ct.erl
- test/epgsql_cth.erl
See #142 for details.
https://github.com/sfackler/rust-postgres/blob/master/postgres-protocol/src/authentication/sasl.rs and https://github.com/npgsql/npgsql/pull/1769/files were used as references.
Code that implements authentication was reworked so it should be easier to add any new auth methods.
scram-sha-256 auth method was added to Postgresql 10 and not available on earlier postgresql releases.
However, it seems that travis-ci doesn't support PG10 yet https://github.com/travis-ci/travis-ci/issues/8537, so, we can't test this on travis, but I checked it locally.
> Scram sha auth

- .travis.yml
- Makefile
This is a small workaround for rebar3 R16 incompatibilities introduced after Rebar3 3.5.2.
But if we would decide to drop R16 support (see #162), this PR won't be needed
> Use R16-compatible rebar3 on R16

- src/datatypes/epgsql_codec_bpchar.erl
- test/epgsql_SUITE.erl
Accept string as `bpchar` parameter. Fixes #159
> Fix bpcahar parameter is list. Fixes #159

- src/epgsql_binary.erl
- test/epgsql_SUITE.erl
Currently in 4+ decoding of nested structures is broken:
```erlang repl
1> epgsql:equery(C, "select (1, (select (2,3)));", []).
{ok,[{column,<<"row">>,{unknown_oid,2249},2249,-1,-1,1}],
[{{1,
<<0,0,0,2,0,0,0,23,0,0,0,4,0,0,0,2,0,0,0,23,0,0,...>>}}]}
```
```erlang repl
2> epgsql:equery(C, "select (1, '{2,3}'::int[]);", []).
13:20:28.949 [error] CRASH REPORT Process <0.17684.0> with 0 neighbours crashed with reason: no function clause matching epgsql_codec_integer:decode(<<0,0,0,1,0,0,0,0,0,0,0,23,0,0,0,2,0,0,0,1,0,0,0,4,0,0,0,2,0,0,0,4,0,0,0,3>>, int4, []) line 36
```
> Bugfix decoding of nested records and arrays

- README.md
- src/commands/epgsql_cmd_connect.erl
- src/epgsql.erl
- src/epgsqla.erl
- src/epgsqli.erl
Some people are disappointed by the fact, that if `connect` command crashes (eg, database is down), database password will be dumped as plaintext to SASL crash log.
In this PR I obfuscate password before sending it to epgsql_sock process by wrapping it into anonymous fun.
If password is already fun, it's passed as is. So, since now it's possible to provide password as fun with no arguments.
Fun only lives as long as `connect` command executing, so, it shouldn't be a problem for hot code upgrade.
Before:
```
$ rebar3 shell
===> Verifying dependencies...
===> Compiling epgsql
Erlang/OTP 20  [erts-9.1.5] [source-790ce75415] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [kernel-poll:false]
Eshell V9.1.5  (abort with ^G)
1> epgsql:connect(#{host => "localhost", port => 5431, username …
```
> Hide password in crash report

- rebar.config
- src/epgsql.erl
- src/epgsql_oid_db.erl
- src/epgsql_scram.erl
The main reason for this change is to make it possible to build epgsql on all supported OTP releases even without rebar and `paltform_define` applied.
But as a bonus, `platform_define` is now looks much simpler.
> Simplify `platform_define` rebar configs

- src/epgsql.erl
Realized that epgsql:connect/5 wasn't updated to refer to `Password :: password()`
> Also fix typespec for epgsql:connect/5

- src/epgsql.erl
I recently encountered a bug in one of my projects which would have been caught by dialyzer if we had a spec for `epgsql:equery/3`. I suspect that `epgsql:equery/3` used to call `epgsql:equery/4` (which does have a spec) but since it no longer has, dialyzer doesn't know the spec anymore. 
It might make sense to add a `warn_missing_spec` in order to enforce specs on all exported functions. @seriyps how do you feel about that? In that case, I can work on a PR that introduces specs for all exported functions and avoid these small PRs :) The thing though is that many of the exported functions are only used internally across epgsql modules so it'd be more for internal reasons than for users of this library.
> Add type spec for epgsql:equery/3

- .travis.yml
Just added freshly released Erlang to travis builds
> Add Erlang 22 to travis; replace 21.0 with 21.3

- .travis.yml
- rebar.config
- src/epgsql_oid_db.erl
- src/epgsql_scram.erl
This PR contains 3 not strictly related changes:
- Dropped support for Erlang 17
- Use PostgreSQL 10 server in travis tests
- erlexec test dependency is fetched from hex.pm and upgraded
> Drop erl17 support

- src/datatypes/epgsql_codec_intrange.erl
- src/datatypes/epgsql_codec_timerange.erl
- test/epgsql_SUITE.erl
Fix encode/decode for epgsql_codec_intrange and epgsql_codec_timerange.
Before this fix following selects end with a error:
```
epgsql:equery(Conn, "SELECT tstzrange(current_timestamp, null)").
epgsql:equery(Conn, "SELECT int4range(1, 1)").
```
> fix range codecs

- .travis.yml
New version of "elvis" doesn't support OTP-18. This causes the build to fail:
```
===> Compiling katana_code
===> Compiling _build/lint/plugins/katana_code/src/ktn_io_string.erl failed
_build/lint/plugins/katana_code/src/ktn_io_string.erl:11: syntax error before: ':='
_build/lint/plugins/katana_code/src/ktn_io_string.erl:66: type state() undefined
===> Plugin rebar3_lint not available. It will not be used.
===> Command lint not found
make: *** [elvis] Error 1
```
Let's skip elvis checkrun on OTP-18
> Fix broken build on OTP-18

- README.md
- src/epgsql.erl
So, there will be no need to call `describe` each time - less round-trips.
> Make it possible to provide `#statement{}` to `epgsql:prepared_query/3`

- README.md
- include/epgsql.hrl
- src/epgsql_wire.erl
- test/epgsql_SUITE.erl
PostgreSQL `RowDescription` message [contains](https://www.postgresql.org/docs/12/protocol-message-formats.html) information about result column's database table and column location.
This commit exposes this data as 2 new fields of `#column{}` record:
- table_oid
If the field can be identified as a column of a specific table, the OID of the table; otherwise zero.
- table_attr_number
If table_oid is not zero, the attribute number of the column; otherwise zero.
Thos fields are exposed by, eg, [Python's psycopg2](https://www.psycopg.org/docs/extensions.html#psycopg2.extensions.Column.table_oid).
> Add table metadata to #column{} record

- README.md
- rebar.config
- src/commands/epgsql_cmd_batch.erl
- src/epgsql.erl
- src/epgsqla.erl
- src/epgsqli.erl
- test/epgsql_SUITE.erl
- test/epgsql_cast.erl
- test/epgsql_incremental.erl
It is useful when there is a need to execute the same query with a different sets of parameters.
The most obvious example is batch insert:
```erlang
RowsToInsert = [
["Joe", 35],
["Paul", 26],
["Mary", 24],
...
],
{_Cols, [{ok, [{1}]}, {ok, [{2}]} | _ ]} = 
epgsql:execute_batch(
C, "INSERT INTO account (name, age) VALUES ($1, $2) RETURNING id", 
RowsToInsert)
```
The one controversal detail that I'm not sure about is when to return `[#columns{}]`? Because they are only needed when 2nd argument is sql query string. Otherwise they can be extracted from `Statement#statement.columns`.
There are options:
1. Don't return columns at all (in this case one who needs them will have to use `parse` + `execute_batch`)
2. Always return `{Cols, Results}` - as it is implemented in this PR
3. Return …
> Introduce epgsql{a,i}:execute_batch/3

- Makefile
Fail the build if coverage falls below 55%
Would be nice to raise this bar in the future.
> Enable test-coverage

- README.md
- rebar.config
- src/datatypes/epgsql_codec_hstore.erl
- test/epgsql_SUITE.erl
There was a TODO in hstore codec to be able to choose output format, so now `return` controls output format (map / jiffy / prolist)
Also, `nulls` option that controls NULL terms, similar to what was added in #212
> Add `return` and `nulls` options to hstore codec

- src/epgsql.erl
- src/epgsql_sock.erl
Replaces https://github.com/epgsql/epgsql/pull/216 due to the branch name on that PR no longer describing the change correctly.
> Response types for epgsql:equery/[2-4] and epgsql:squery/2 can include socket errors

- .gitignore
- README.md
- src/commands/epgsql_cmd_connect.erl
Hi,
I was looking through the `epgsql:connect/x` and stumbled upon the connection_timeout. 
`epgsql:connect/x` accepts "timeout" as a property under the `Opts`. 
However, this property is not respected while trying to establish a connection under `epgsql_cmd_connect:execute/2` since this function calls `gen_tcp:connect` and `ssl:connect` with the same Timeout. In the worst case scenario we might end up with almost 2*Timeout as our connection timeout.
This PR tries to address this issue.
Please let me know if I missed something.
> Do not re-use the same connection timeout during different steps of establishing the connection

- include/protocol.hrl
- src/epgsql_sock.erl
Another alternative is to send it from `terminate` gen_server callack. Don't have a strong opinion, so, decided to start with obviously gracefull case with option to make it more generic later.
> Send `Terminate` mesage when performing gracefull shutdown. Fixes #215

- src/datatypes/epgsql_codec_integer.erl
- src/datatypes/epgsql_codec_intrange.erl
- test/epgsql_SUITE.erl
See #202 .
In this implementation we just crash a connection. Less destructive error reporting can be introduced later if desired.
> Add guards to not silently truncate integer when overflowed. Fixes #202

- README.md
- src/commands/epgsql_cmd_connect.erl
- src/epgsql_sock.erl
- test/epgsql_SUITE.erl
Hi,
Looking at the `epgsql:cancel/x` it appears like `epgsql` opens a new temporary TCP connection and sends the cancellation request. This is fine for applications which uses normal non-TLS connections. 
However, if we are dealing with an application which uses TLS connections for all its queries except for the cancellation request then we might open ourselves to the man-in-the-middle-attack.
The attacker can in theory listen to our cancellation request and detect the previously generated secret key during the connection establishment of the original connection.
Once the attacker gets hold of that key while the original connection can still accept queries even after its last query was cancelled then the attacker can in theory cancel all the queries fired from the original connection. …
> Handle tls connection during cancellation

- README.md
- src/commands/epgsql_cmd_batch.erl
- test/epgsql_SUITE.erl
This PR tries to address the problem raised by #186 .
Whenever `epgsql/i/a:execute_batch` is being called with several statements/sql_queries and PG returns an error for one statement then epgsql would return an error on unexpected message 90 ("Z").
The only exception to this rule is if you call `epgsql/i/a:execute_batch` with a list of three statements where the first one is successful, the second crashes and the third will be skipped. But had it been a fourth statement it would have crashed.
With the changes introduced in this PR epgsql won't return an error unexpected_message but rather a list of type [ {ok, result()}, {error, [ {error, #error{}}, {error, skipped} ] } ].
There will be as many {error, skipped} as many statements were not executed from PG.
> Handle skipped commands in execute_batch

- .travis.yml
Since OTP 23 is the last stable Erlang version, it makes sense to test it.
I'm more concerned about the fact that CI only uses PostgreSQL 10, while both 11 and 12 are available and used everywhere. I'm not sure on how to test multiple Pg versions in Travis though.
> test with otp 23 in travis

- src/epgsql_scram.erl
close #235
It could be made cleaner and simpler by dropping support for OTP<21 (which introduced the `OTP_RELEASE` macro if I'm not mistaken). I fail to see the point in supporting releases that old.
> switch to crypto:mac/4 since crypto:hmac/3 is deprecated

- Makefile
- README.md
- src/commands/epgsql_cmd_connect.erl
- src/epgsql.erl
See #240. I also decided to turn off all "smart" socket option tuning (eg, `keepalive`, `buffer`) when user provides `tcp_opts` to provide more flexibility.
> Add `tcp_opts` connect option

- doc/pluggable_commands.md
- src/commands/epgsql_cmd_batch.erl
- src/commands/epgsql_cmd_bind.erl
- src/commands/epgsql_cmd_close.erl
- src/commands/epgsql_cmd_connect.erl
- src/commands/epgsql_cmd_describe_portal.erl
- src/commands/epgsql_cmd_describe_statement.erl
- src/commands/epgsql_cmd_equery.erl
- src/commands/epgsql_cmd_execute.erl
- src/commands/epgsql_cmd_parse.erl
- src/commands/epgsql_cmd_prepared_query.erl
- src/commands/epgsql_cmd_squery.erl
- src/commands/epgsql_cmd_start_replication.erl
- src/commands/epgsql_cmd_sync.erl
- src/commands/epgsql_cmd_update_type_cache.erl
- src/epgsql_command.erl
- src/epgsql_sock.erl
- src/epgsql_wire.erl
Some cleanups of `epgsql_command` interface and implementations
* It's now possible to return `{send, ...}` or `{send_multi, ...}` from command's `execute` callback instead of caling `epgsql_sock:send` / `epgsql_sock:send_multi`, because most of the commands call those functions in the end anyway
* Some helper functions added to construct Client -> Server packets
> Command api improvements

- include/protocol.hrl
- src/commands/epgsql_cmd_copy_done.erl
- src/commands/epgsql_cmd_copy_from_stdin.erl
- src/commands/epgsql_cmd_start_replication.erl
- src/epgsql.erl
- src/epgsql_copy.hrl
- src/epgsql_sock.erl
- src/epgsql_wire.erl
- test/epgsql_copy_SUITE.erl
All 3 formats are supported: text, CSV, binary. Partially solves #137.
For text-based formats the way you send COPY payload is to epgsql is by using Erlang IO-protocol (so, standard library functions like `io:put_chars`, `io:format/3`, `file:write` can be used).
For binary format a special function was introduced: `epgsql:copy_send_rows/3`. It takes care of encoding Erlang values to postgresql binary format. It should be possible to use IO-protocol to transfer binary format as well (so, encoding is done bu the user), but I haven't provided any helpers or tests for that.
A lot of examples you can find in the tests, new epgsql_copy_SUITE test suite was introduced.
I'm still not sure if the `epgsql:copy_from_stdin` function should take raw SQL query OR take some map with parameters and …
> COPY .. FROM STDIN

- Makefile
- README.md
- test/epgsql_SUITE.erl
- test/epgsql_cast.erl
- test/epgsql_incremental.erl
epgsql supports pipelining (send multiple requests without waiting for response), but we haven't had tests for it.
also, test for "mixed api" scenarios - using `epgsql`, `epgsqla` and `epgsqli` with the same connection
> Pipelined and mixed api tests

- src/epgsql_scram.erl
Found out that `-if` works not as `-if(MACRO_NAME..)` but as `-if(?MACRO_NAME ...)`. So, epgsql crashes on OTP-24 release candidate
> Fix `-if(?OTP_RELEASE)` (was missing question mark)

- README.md
- src/commands/epgsql_cmd_connect.erl
- test/epgsql_SUITE.erl
* Seems TLS-1.3 connection is not failing immediately when connecting with
invalid TLS client certificate
* `active => false` option seems lost after TCP->TLS upgrade
I've seen similar issues (some of socket options reset after SSL upgrade) in gen_smtp project: https://github.com/gen-smtp/gen_smtp/pull/273#discussion_r693170598
> Some tests involving TLS were unstable on CI on some Erlang versions

- .github/workflows/ci.yml
All the other tests are running on PostgreSQL-10, because this is the one available on Ubuntu 18.04. Here we are introducing one more test on Ubuntu 20.04 and PostgreSQL 12.
CI might be unstable right now, needs to be rebased on #263 when merged.
> Add PostgreSQL-12 on Ubuntu 20.04 and OTP-24 to CI

- src/epgsql.erl
- src/epgsql_sock.erl
- src/epgsqla.erl
- src/epgsqli.erl
- test/epgsql_SUITE.erl
- test/epgsql_cast.erl
- test/epgsql_incremental.erl
It's similar to `SELECT pg_backend_pid()`, but does not need network roundtrip and can be called even when thefre is an asynchronous query is still running.
> Add `get_os_pid/1` function

- README.md
- doc/streaming.md
- src/commands/epgsql_cmd_connect.erl
- src/epgsql.erl
- src/epgsql_sock.erl
- test/epgsql_cth.erl
- test/epgsql_replication_SUITE.erl
This implements support of `{active, N}` where `N ∈ [-32768, 32767]` on TCP and SSL (since OTP 21.3) sockets.
It makes possible to limit incoming data flow and activate it again on-demand.
> A flow control in the replication streaming mode

- README.md
- doc/streaming.md
- src/commands/epgsql_cmd_connect.erl
- src/epgsql.erl
- src/epgsql_sock.erl
- test/epgsql_SUITE.erl
- test/epgsql_incremental.erl
- test/epgsql_replication_SUITE.erl
In #275 `socket_active` option have been implemented for the streaming replication mode. In this PR I expand this option usage to any possible epgsql mode.
It may also partially fix #230
> Generalize socket active n

- .github/workflows/ci.yml
- src/epgsql_sock.erl
- test/epgsql_SUITE.erl
- test/epgsql_ct.erl
Add testcase on correctly redacted state.
Also mention that `format_status/2` callback is deprecated since OTP-25.
> Support blessed `format_status/1` callback 

- src/commands/epgsql_cmd_squery.erl
- test/epgsql_SUITE.erl
If squery request contains `select` and than `insert` or `delete` without returning the response of `insert` or `delete` must not contain any columns.
Now:
```sql
select table1_column from table1;
insert into table2 (table2_column) values (1);
delete from table3 where table3_column = 3;
```
will return
```erlang
[
{ok, [#column{name = <<"table1_column">>}], [{1}]},
{ok, 1, [#column{name = <<"table1_column">>}]}, []},
{ok, 1, [#column{name = <<"table1_column">>}]}, []}
]
```
Expected result:
```erlang
[
{ok, [#column{name = <<"table1_column">>}], [{1}]};
{ok, 1};
{ok, 1};
]
```
> Fix issue with columns in multiple squery response

- Makefile
- src/commands/epgsql_cmd_batch.erl
- src/commands/epgsql_cmd_copy_from_stdin.erl
- src/epgsql.erl
- src/epgsql_binary.erl
- src/epgsql_copy.hrl
- src/epgsql_sock.erl
- src/epgsql_wire.erl
- test/data/test_schema.sql
- test/epgsql_SUITE.erl
- test/epgsql_copy_SUITE.erl
Before the only way to encode Erlang term to PostgreSQL binary format was to use `epgsql_wire:encode_parameters` that calls `epgsql_binary:encode/3` in a loop. The problem is that `epgsql_binary:encode/3` does quite a lot of `codec()` database lookups and structure transformations and this process repeats for each parameter.
It worked quite ok for normal `equery`, because you usually don't send too many parameters to it. But now with introduction of `COPY .. FROM STDIN WITH (FORMAT binary)` we might need to encode a lot of rows of the same structure. So it makes sense to do all the OID table lookups in advance.
The same optimization was applied to `execute_batch/3`, because we use the same statement for multiple rows.
1st commit optimizes COPY, 2nd optimizes `execute_batch`
> Optimize batch encoder
